#!/usr/bin/bash
PATH=/bin:/usr/bin
#xtrace
#set -x
#Verbose
#set -v 

if grep "$1" /home/user/daylogs/0412 >/dev/null 2>/dev/null
then
   echo Match "$1"
   exit 0
else
   echo Did not match "$1"
fi





